---
- name: Install postfix
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - postfix
    - mailutils

- name: Overlay postfix sasl password maps
  template:
    src: sasl_passwd.j2
    dest: /etc/postfix/sasl_passwd
    mode: 0600
  notify: postmap sasl_passwd
  when:
    - postfix_parameters.relayhost is defined
    - postfix_parameters.smtp_sasl_password_maps is defined
    - postfix_sasl_password is defined
    - postfix_sasl_username is defined

- name: Update Postfix configuration.
  template:
    src: main.cf.j2
    dest: "{{ postfix_config_file }}"
    mode: 0644
  notify: restart postfix

- name: Ensure postfix is started and enabled at boot.
  service:
    name: postfix
    state: "{{ postfix_service_state }}"
    enabled: "{{ postfix_service_enabled }}"
